apiVersion: v1
entries:
  delay:
  - apiVersion: v2
    appVersion: v1
    created: "2023-08-23T20:52:13.933085+08:00"
    description: 用flask制作的超级简单的一个随机0-10秒时延的小程序，无状态，可以多机部署
    digest: 9943ad83e8678eea317cf36ea2a63a5288c7e2add562f3d6817642f80d9f2665
    name: delay
    type: application
    urls:
    - https://cqsuper.github.io/helm/delay-0.1.0.tgz
    version: 0.1.0
  ops:
  - apiVersion: v2
    appVersion: v4
    created: "2023-08-23T20:52:13.933817+08:00"
    description: A Helm chart for Kubernetes
    digest: f85eb24d026a3def8c2bcf433105365e349156de005ee49b1daa462d2846b648
    name: ops
    type: application
    urls:
    - https://cqsuper.github.io/helm/ops-0.1.0.tgz
    version: 0.1.0
  tmall:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-08-23T20:52:13.934627+08:00"
    description: tmall demo
    digest: d4270e3bdf75f4926f0192422f3c9ae7448de567d6b4024594e3a4804684fe9a
    name: tmall
    type: application
    urls:
    - https://cqsuper.github.io/helm/tmall-0.1.5.tgz
    version: 0.1.5
generated: "2023-08-23T20:52:13.932202+08:00"
